((nil . ((bug-reference-url-format . "https://github.com/alex-hhh/map-widget/issues/%s")
         (bug-reference-bug-regexp . "\\#\\(?2:[0-9]+\\)\\>")
         (indent-tabs-mode         . nil)
         (require-final-newline    . t)
         (show-trailing-whitespace . t)
         (ah-project-headline . "map-widget -- A Racket GUI Widget to display maps based on OpenStreetMap tiles")
         (ah-project-license . lgpl)))
 (yaml-mode . ((mode . goto-address)
               (mode . bug-reference)))
 (shell-script-mode . ((mode . goto-address)
                       (mode . bug-reference)))
 (log-edit-mode . ((mode . goto-address)
                   (mode . bug-reference)))
 (markdown-mode . ((mode . goto-address)
                   (mode . bug-reference)))
 (racket-mode . ((mode . goto-address)
                 (mode . bug-reference)))
 (sql-mode . ((mode . goto-address)
              (mode . bug-reference)
              (sql-product . sqlite))))
